//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string package { get; set; }
        public string target { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
