//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gym_classes
    {
        public int class_id { get; set; }
        public string class_name { get; set; }
        public string instructor { get; set; }
        public string schedule { get; set; }
        public Nullable<int> max_capacity { get; set; }
        public Nullable<int> current_enrollment { get; set; }
    }
}
