//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string images { get; set; }
        public string author { get; set; }
        public System.DateTime posting_date { get; set; }
        public Nullable<int> likes { get; set; }
        public string status { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> client_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Client Client { get; set; }
    }
}
